### ISSUE TITLE
Publish wheels for `pylibtiff`

### ISSUE THREAD

**Issue by mcovalt** [girder/large_image_wheels#29]
See https://github.com/girder/large_image/pull/799.

The choice of `libtiff` and `pylibtiff` are both valid since both packages exist on PyPI. Currently we only produce `libtiff`.

**Comment by manthey** [comment]
Curiously, libtiff changed its release name to pylibtiff a few minor releases ago, but we didn't follow (even though everything else is kept up to date).  I think we can stop producing the libtiff package and just produce pylibtiff.
