### ISSUE TITLE
Add Python 3.11 wheels

### ISSUE THREAD

**Issue by EwoutH** [girder/large_image_wheels#31]
[Python 3.11](https://docs.python.org/3.11/whatsnew/3.11.html) is now in release candidate phase and will be released in two weeks. Support is ramping up, both in the scientific suite (with NumPy, Pandas, SciPy, Matplotlib and Seaborn already supporting 3.11, among others), as well in the geospatial suite (with Shapely CI is passing and Fiona working on it). It would be great if large_image_wheels could provide wheels for Python 3.11!

**Comment by manthey** [comment]
Yes.  I should have noticed that numpy started publishing 3.11 wheels in August, which is the necessary antecedent to making these wheels.  I'll push 3.11 wheels soon and they should be available in a few hours.

**Comment by EwoutH** [comment]
Thanks for the quick response, that's awesome!

**Comment by EwoutH** [comment]
Looks like the CI didn't pass, did it?

**Comment by manthey** [comment]
GitHub pages is being more restrictive than it used to be -- it now fails when trying to publish in the current technique.  It'll take a little bit for me to refactor the deployment to make it update.

**Comment by EwoutH** [comment]
Yes, thanks a lot!
